version: '3.3'
services:
  database:
    image: mariadb:10.5
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./data/init.d:/docker-entrypoint-initdb.d
      - mariadb_data:/bitnami/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      
  web:
    build: ./web
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - database
    env_file:
      - .env
    environment:
      MAFIASCUM_ENVIRONMENT: staging
    volumes:
      - phpbb_data:/bitnami/phpbb
      
volumes:
  mariadb_data:
      driver: local
  phpbb_data:
      driver: local