version: '3.3'
services:
  database:
    build: ./database
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      
  web:
    build: ./web
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - wiki_data:/data/wiki
      - phpbb_data:/data/forum
      - access_logs:/etc/apache2/logs
      - ./web/apache/httpd.conf:/etc/apache2/conf-enabled/httpd.conf
      - ./web/apache/usertrack.conf:/etc/apache2/conf-enabled/usertrack.conf
      - ./web/apache/remoteip.conf:/etc/apache2/conf-enabled/remoteip.conf


  sitechat:
    image: mafiascum/site-chat-server
    restart: always
    depends_on:
      - database
    env_file:
      - .env

  sphinx:
    build: ./sphinx
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - sphinx_data:/var/lib/sphinxsearch/data
      - ./sphinx/config/sphinx.conf:/etc/sphinxsearch/sphinx.conf.template
      - ./sphinx/cron.d:/etc/cron.d.template
    environment:
      SPHINX_MODE: indexing

  nginx:
    image: staticfloat/nginx-certbot
    restart: always
    depends_on:
      - web
      - sitechat
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      ENVSUBST_VARS: ROOT_FQDN WWW_FQDN FORUM_FQDN WIKI_FQDN SITECHAT_FQDN
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt_data:/etc/letsencrypt
    
  postfix:
    image: boky/postfix
    env_file:
      - .env
    restart: always

volumes:
  mariadb_data:
    driver: local
  phpbb_data:
    driver: local
  wiki_data:
    driver: local
  letsencrypt_data:
    driver: local
  sphinx_data:
    driver: local
  access_logs:
    driver: local
