version: '3.3'
services:
  database:
    build: ./database
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      
  web:
    build: ./web
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - wiki_data:/bitnami/wiki
      - phpbb_data:/bitnami/phpbb

  nginx:
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt_data:/etc/letsencrypt
    
volumes:
  mariadb_data:
    driver: local
  phpbb_data:
    driver: local
  wiki_data:
    driver: local
  letsencrypt_data:
    driver: local