version: '3.3'
services:
  database:
    build: ./database
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.40.0.10
      
  web:
    build:
      context: ./web
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - wiki_data:/data/wiki
      - phpbb_data:/data/forum
      - access_logs:/etc/apache2/logs
      - ./web/apache/httpd.conf:/etc/apache2/conf-enabled/httpd.conf
      - ./web/apache/usertrack.conf:/etc/apache2/conf-enabled/usertrack.conf
      - ./web/apache/remoteip.conf:/etc/apache2/conf-enabled/remoteip.conf
    networks:
      backend:
        ipv4_address: 172.40.0.11

  web-alt:
    build:
      context: ./web
    restart: "no"
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - wiki_data:/data/wiki
      - phpbb_data:/data/forum
      - access_logs:/etc/apache2/logs
      - ./web/apache/httpd.conf:/etc/apache2/conf-enabled/httpd.conf
      - ./web/apache/usertrack.conf:/etc/apache2/conf-enabled/usertrack.conf
      - ./web/apache/remoteip.conf:/etc/apache2/conf-enabled/remoteip.conf
    networks:
      backend:
        ipv4_address: 172.40.0.12


  sitechat:
    image: mafiascum/site-chat-server
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.40.0.13

  sphinx:
    build: ./sphinx
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - sphinx_data:/var/lib/sphinxsearch/data
      - ./sphinx/config/sphinx.conf:/etc/sphinxsearch/sphinx.conf.template
      - ./sphinx/cron.d:/etc/cron.d.template
    environment:
      SPHINX_MODE: indexing
    networks:
      backend:
        ipv4_address: 172.40.0.14

  nginx:
    image: staticfloat/nginx-certbot
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      ENVSUBST_VARS: ROOT_FQDN WWW_FQDN FORUM_FQDN WIKI_FQDN SITECHAT_FQDN
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-blue.conf:/etc/nginx/nginx-blue.conf:ro
      - ./nginx/nginx-green.conf:/etc/nginx/nginx-green.conf:ro
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt_data:/etc/letsencrypt
    networks:
      backend:
        ipv4_address: 172.40.0.2

  social-games:
    build:
      context: ./social-games
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - social_games_www:/var/www/html
    networks:
      backend:
        ipv4_address: 172.40.0.16

volumes:
  mariadb_data:
    driver: local
  phpbb_data:
    driver: local
  wiki_data:
    driver: local
  letsencrypt_data:
    driver: local
  sphinx_data:
    driver: local
  access_logs:
    driver: local
  social_games_www:
    driver: local

networks:
  backend:
    ipam:
      config:
        - subnet: 172.40.0.0/16