version: '3.3'
services:
  database:
    build: ./database
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      
  web:
    build: ./web
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - wiki_data:/bitnami/wiki
      - phpbb_data:/bitnami/phpbb

volumes:
  mariadb_data:
      driver: local
  phpbb_data:
      driver: local
  wiki_data:
      driver: local