version: '3.3'
services:
  database:
    build: ./database
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      
  web:
    build: ./web
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - wiki_data:/bitnami/wiki
      - phpbb_data:/bitnami/phpbb

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    env_file:
      - .env
    volumes:
      ./data/certbot/conf:/etc/letsencrypt
      ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      ./data/certbot/conf:/etc/letsencrypt
      ./data/certbot/www:/var/www/certbot
    
volumes:
  mariadb_data:
    driver: local
  phpbb_data:
    driver: local
  wiki_data:
    driver: local