add_user_as_slot_route:
  path: /add_user_as_slot
  defaults:
    {
      _controller: mafiascum.votecounter.votecountSettingsController:add_user_as_slot,
    }
remove_slot_route:
  path: /remove_slot
  defaults:
    {
      _controller: mafiascum.votecounter.votecountSettingsController:remove_slot,
    }
