<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
} elseif ( empty( $wgNoOutputBuffer ) ) {
	## Compress output if the browser supports it
	if( !ini_get( 'zlib.output_compression' ) ) @ob_start( 'ob_gzhandler' );
}

$wgServer           = getenv('PHPBB_FORUM_SERVER_PROTOCOL') . getenv('WIKI_FQDN');
$wgSitename         = "MafiaWiki";

$wgScriptPath	    = "";
$wgScript           = "$wgScriptPath/index.php";
$wgRedirectScript   = "$wgScriptPath/redirect.php";

## For more information on customizing the URLs please see:
## http://meta.wikimedia.org/wiki/Eliminating_index.php_from_the_url
## If using PHP as a CGI module, the ?title= style usually must be used.
# $wgArticlePath      = "$wgScript/$1";
$wgArticlePath      = "$wgScript?title=$1";

$wgStylePath        = "$wgScriptPath/skins";
$wgStyleDirectory   = "$IP/skins";
$wgLogo             = "$wgScriptPath/images/b/bc/Wiki.png";

$wgUploadPath       = "$wgScriptPath/images";
$wgUploadDirectory  = "$IP/images";

$wgEnableEmail = false;
$wgEnableUserEmail = false;

$wgEmergencyContact = "mith@mafiascum.net";
$wgPasswordSender	= "mith@mafiascum.net";

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

$wgDBserver         = getenv("PHPBB_DATABASE_HOST");
$wgDBname           = getenv("WIKI_DATABASE_NAME");
$wgDBuser           = getenv("PHPBB_DATABASE_USER");
$wgDBpassword       = getenv("PHPBB_DATABASE_PASSWORD");
$wgDBprefix         = "";
$wgDBtype           = "mysql";
$wgDBport           = getenv("PHPBB_DATABASE_PORT_NUMBER");

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

# Enable subpages in the main namespace.  Turned on by -JEEP 4 MAR 2007
$wgNamespacesWithSubpages[NS_MAIN] = 1;

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads		= true;
$wgUseImageResize		= true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX	         = false;
$wgMathPath         = "{$wgUploadPath}/math";
$wgMathDirectory    = "{$wgUploadDirectory}/math";
$wgTmpDirectory     = "{$wgUploadDirectory}/temp";

$wgCookieExpiration = 150*86400;
$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "663fc8a99474b2bfc2ff5bc042ab7c5b597edc656c1fd194e1aa5b6116946f86";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'vector';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

// Allow user to edit their talk pages when blocked.
$wgBlockAllowsUTEdit = true;

# Restrict editing of wiki to registered users - added by mith 17 Dec 2010

$wgGroupPermissions['*']['edit'] = false;

#Allow user style code; enabled by -JEEP 4 Mar 2007
$wgAllowUserJs  = true;
$wgAllowUserCss  = true;

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );

# $wgReadOnlyFile = "wikilock.txt";


function removeExportSpecial(&$aSpecialPages)
{
        unset($aSpecialPages['Export']);
        return true;
}
$wgHooks['SpecialPage_initList'][] = 'removeExportSpecial';

$wgAuth_Config = array(); // Clean.

$wgAuth_Config['WikiGroupName'] = 'Wiki';       // Name of your PHPBB group
                                                // users need to be a member
                                                // of to use the wiki. (i.e. wiki)
                                                // This can also be set to an array
                                                // of group names to use more then
                                                // one. (ie.
                                                // $wgAuth_Config['WikiGroupName'][] = 'Wiki';
                                                // $wgAuth_Config['WikiGroupName'][] = 'Wiki2';
                                                // or
                                                // $wgAuth_Config['WikiGroupName'] = array('Wiki', 'Wiki2');
                                                // )

$wgAuth_Config['UseWikiGroup'] = false;          // This tells the Plugin to require
                                                // a user to be a member of the above
                                                // phpBB group. (ie. wiki) Setting
                                                // this to false will let any phpBB
                                                // user edit the wiki.

$wgAuth_Config['UseExtDatabase'] = true;       // This tells the plugin that the phpBB tables
                                                // are in a different database then the wiki.
                                                // The default settings is false.

$wgAuth_Config['MySQL_Host']        = getenv("PHPBB_DATABASE_HOST");      // phpBB MySQL Host Name.
$wgAuth_Config['MySQL_Username']    = getenv("PHPBB_DATABASE_USER");      // phpBB MySQL Username.
$wgAuth_Config['MySQL_Password']    = getenv("PHPBB_DATABASE_PASSWORD");       // phpBB MySQL Password.
$wgAuth_Config['MySQL_Database']    = getenv("PHPBB_DATABASE_NAME");      // phpBB MySQL Database Name.

$wgAuth_Config['UserTB']         = 'phpbb_users';       // Name of your PHPBB user table. (i.e. phpbb_users)
$wgAuth_Config['GroupsTB']       = 'phpbb_groups';      // Name of your PHPBB groups table. (i.e. phpbb_groups)
$wgAuth_Config['User_GroupTB']   = 'phpbb_user_group';  // Name of your PHPBB user_group table. (i.e. phpbb_user_group)
$wgAuth_Config['PathToPHPBB']    = '../phpbb/';         // Path from this file to your phpBB install. Must end with '/'.

// Local
// $wgAuth_Config['LoginMessage']   = '<b>You need a phpBB account to login.</b><br /><a href="' . $wgAuth_Config['PathToPHPBB'] .
//				    'ucp.php?mode=register">Click here to create an account.</a>'; // Localize this message.
$wgAuth_Config['LoginMessage']   = '<b>You need a phpBB account to login.</b><br /><a href="http://forum.mafiascum.net/ucp.php?mode=register">Click here to create an account.</a>'; // Localize this message.
$wgAuth_Config['NoWikiError']    = 'You are not a member of the required phpBB group.'; // Localize this message.

$wgNoFollowDomainExceptions = array( 
        getenv('ROOT_FQDN'),
        getenv('WWW_FQDN'),
        getenv('FORUM_FQDN'),
        getenv('WIKI_FQDN')
);

wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'Auth_phpBB' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'WikiSEO' );
wfLoadExtension( 'AbuseFilter' );
wfLoadExtension( 'DeleteBatch' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'intersection' );

$wgGroupPermissions['sysop']['nuke'] = false;
$wgGroupPermissions['nuke']['nuke'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['sysop']['abusefilter-log-detail'] = true;
$wgGroupPermissions['sysop']['abusefilter-view'] = true;
$wgGroupPermissions['sysop']['abusefilter-log'] = true;
$wgGroupPermissions['sysop']['abusefilter-private'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['sysop']['abusefilter-revert'] = true;

?>
