services:
    mafiascum.bbcodes.listener:
        class: mafiascum\bbcodes\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '@notification_manager'
            - '@language'
        tags:
            - { name: event.listener }
    notification.type.mention:
        class: mafiascum\bbcodes\notification\type\mention
        shared: false
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
        calls:
            - [set_notification_manager, ['@notification_manager']]
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }

    mafiascum.bbcodes.helper:
        class: mafiascum\bbcodes\includes\helper
        arguments:
            - '@dbal.conn'
            - '@filesystem'
            - '%core.root_path%'
            - '%core.php_ext%'