services:
    mafiascum.isos.listener:
        class: mafiascum\isos\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
    mafiascum.isos.controller:
        class: mafiascum\isos\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@request'